version: 0.2
phases:
  pre_build:
    commands:
      - echo "Installing source NPM dependencies..."
      - npm install
      - aws codeartifact login --tool npm --repository sandbox --domain syscloud --domain-owner 538782569624
    finally:
      - echo "Completed installing dependencies"
  build:
    commands:
      - echo "Build started on `date`"
      - npm run doc
      - echo "Done"
      - echo "Getting ready for testing"
      - echo "Running tests"
      - npm test
      - echo "Testing done"
      - npm publish
      - echo "Done, published package."

    finally:
      - echo "Build Successfully"
  post_build:
    commands:
      - aws s3 cp ./docs s3://sys-sandbox-artifacts/Teja/Team2_Task3/docs --recursive
      - aws s3 cp ./coverage s3://sys-sandbox-artifacts/Teja/Team2_Task3/coverage --recursive
    finally:
      - echo "Build_End_Date on `date`"
artifacts:
  files:
    - docs/**/*
    - coverage/**/*
